/** Canonical origin. Open Graph and Twitter card images must be absolute URLs —
 *  crawlers do not resolve the relative paths Vite emits for imported assets. */
export const SITE_URL = "https://ahuriri-haven-booking.vercel.app";

/** Share card image — public/og-image.jpg, generated by scripts/make-icons.mjs. */
export const OG_IMAGE = `${SITE_URL}/og-image.jpg`;
export const OG_IMAGE_WIDTH = "1200";
export const OG_IMAGE_HEIGHT = "630";
export const OG_IMAGE_ALT = "H&H Properties — The Vulcan, Ahuriri";
