/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LocationRouteImport } from './routes/location'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as BookRouteImport } from './routes/book'
import { Route as ApartmentRouteImport } from './routes/apartment'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentRoute = ApartmentRouteImport.update({
  id: '/apartment',
  path: '/apartment',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amenities': typeof AmenitiesRoute
  '/apartment': typeof ApartmentRoute
  '/book': typeof BookRoute
  '/hosts': typeof HostsRoute
  '/journal': typeof JournalRouteWithChildren
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/journal/$slug': typeof JournalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amenities': typeof AmenitiesRoute
  '/apartment': typeof ApartmentRoute
  '/book': typeof BookRoute
  '/hosts': typeof HostsRoute
  '/journal': typeof JournalRouteWithChildren
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/journal/$slug': typeof JournalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amenities': typeof AmenitiesRoute
  '/apartment': typeof ApartmentRoute
  '/book': typeof BookRoute
  '/hosts': typeof HostsRoute
  '/journal': typeof JournalRouteWithChildren
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/journal/$slug': typeof JournalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/amenities'
    | '/apartment'
    | '/book'
    | '/hosts'
    | '/journal'
    | '/location'
    | '/reviews'
    | '/journal/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/amenities'
    | '/apartment'
    | '/book'
    | '/hosts'
    | '/journal'
    | '/location'
    | '/reviews'
    | '/journal/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/amenities'
    | '/apartment'
    | '/book'
    | '/hosts'
    | '/journal'
    | '/location'
    | '/reviews'
    | '/journal/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ApartmentRoute: typeof ApartmentRoute
  BookRoute: typeof BookRoute
  HostsRoute: typeof HostsRoute
  JournalRoute: typeof JournalRouteWithChildren
  LocationRoute: typeof LocationRoute
  ReviewsRoute: typeof ReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartment': {
      id: '/apartment'
      path: '/apartment'
      fullPath: '/apartment'
      preLoaderRoute: typeof ApartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
  }
}

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AmenitiesRoute: AmenitiesRoute,
  ApartmentRoute: ApartmentRoute,
  BookRoute: BookRoute,
  HostsRoute: HostsRoute,
  JournalRoute: JournalRouteWithChildren,
  LocationRoute: LocationRoute,
  ReviewsRoute: ReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
